version: 0.2
# env:
#   variables:
#     APP_TARGET_URL: https://qa1.example.com
#   secrets-manager:
#     APP_CREDENTIALS: MySecretsManagerItem:app_credentials
phases:
  install:
    runtime-versions:
      docker: 19
      nodejs: latest
    commands:
      - echo "Login to AWS"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 784470602602.dkr.ecr.us-east-1.amazonaws.com
      - docker pull 784470602602.dkr.ecr.us-east-1.amazonaws.com/selenium-chrome-grid:latest
  pre_build:
    commands:
      - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm --name selenium --network-alias selenium 784470602602.dkr.ecr.us-east-1.amazonaws.com/selenium-chrome-grid:latest
      # - docker exec -u 0 selenium /bin/bash -c 'apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*'
      # - docker exec -d selenium ffmpeg -video_size 1360x1020 -framerate 15 -f x11grab -i :99.0 -vf format=yuv420p /home/seluser/recording.mp4
  build:
    commands:
      - docker build -t 784470602602.dkr.ecr.us-east-1.amazonaws.com/webdriverio-test:latest .
      # - docker push 784470602602.dkr.ecr.us-east-1.amazonaws.com/webdriverio-test:latest
      - docker ps -a
      - docker run --env HOST_NAME=selenium 784470602602.dkr.ecr.us-east-1.amazonaws.com/webdriverio-test:latest
  post_build:
    commands:
      - echo "execution completed"
      # - docker exec selenium pgrep ffmpeg > pidfile
      # - docker exec selenium kill -INT $(cat pidfile)
      # - docker exec selenium /bin/bash -c "while \$(kill -0 $(cat pidfile) 2>/dev/null); do sleep 1; done"
      # - docker cp selenium:/home/seluser/recording.mp4 recording.mp4
# artifacts:
#   files:
#     - recording.mp4
# reports:
#   Selenium:
#     file-format: CucumberJson
#     files:
#       - test-integration/report.json
