version: 0.2
# env:
#   variables:
#     APP_TARGET_URL: https://qa1.example.com
#   secrets-manager:
#     APP_CREDENTIALS: MySecretsManagerItem:app_credentials
phases:
  install:
    runtime-versions:
      docker: 19
      nodejs: latest
    commands:
      - echo "Login to AWS"
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 237245230124.dkr.ecr.us-east-2.amazonaws.com
      - docker pull 237245230124.dkr.ecr.us-east-2.amazonaws.com/selenium-chrome-grid:latest
  pre_build:
    commands:
      - docker network create automation_network || true
      - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm --network automation_network --name selenium --network-alias selenium 237245230124.dkr.ecr.us-east-2.amazonaws.com/selenium-chrome-grid:latest
      # - docker exec -u 0 selenium /bin/bash -c 'apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*'
      # - docker exec -d selenium ffmpeg -video_size 1360x1020 -framerate 15 -f x11grab -i :99.0 -vf format=yuv420p /home/seluser/recording.mp4
  build:
    commands:
      - docker build -t 237245230124.dkr.ecr.us-east-2.amazonaws.com/webdriverio-test:latest .
      # - docker push 784470602602.dkr.ecr.us-east-1.amazonaws.com/webdriverio-test:latest
      - docker ps -a
      - docker create --env HOST_NAME=selenium --network automation_network --name wdio_test --volume "$(pwd)"/reporter:/app/reporter 237245230124.dkr.ecr.us-east-2.amazonaws.com/webdriverio-test:latest
      - docker start -a wdio_test
  post_build:
    commands:
      - echo "execution completed"
      - ls -lrt
      - ls -lrt reporter
      - docker start wdio_test
      - docker exec wdio_test /bin/sh -c "node reporter/index.js ;"
      - ls -lrt reporter
      - ls -lrt reporter/json
artifacts:
  files:
    - reporter/cucumber_report.html
reports:
  WDIO:
    file-format: CucumberJson
    files:
      - reporter/json/*.json
